### ISSUE TITLE
The song doesn't play.

### ISSUE THREAD

**Issue by AI-Avalon** [Hazmi35/jukebox#1066]
Jukebox is expected, but due to YouTube's specification change, it is no longer playable.
We are getting an error document stating that an error occurred while processing the track resource.
I would appreciate it if you could also take a look at the matter I sent you before.

**Comment by KTSnowy** [comment]
`[2022-04-07 17:03:19.047 +0000] ERROR (Shard #0): Cannot read properties of undefined (reading 'response')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'response')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'response')
              at Client.<anonymous> (/root/jukebox-5.5.2/node_modules/youtubei/dist/classes/Client.js:76:35)
              at Generator.next (<anonymous>)
              at fulfilled (/root/jukebox-5.5.2/node_modules/youtubei/dist/classes/Client.js:5:58)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
    }`

currently there's a ` "Cannot read properties of undefined (reading 'response')"` error when trying to play a song from youtube

**Comment by KTSnowy** [comment]
I found a fix for it, updating `youtubei` to the latest version fixes this issue

**Comment by Hazmi35** [comment]
Should be fix in https://github.com/Hazmi35/jukebox/issues/1066, but the issue probably comes up again, please see SuspiciousLookingOwl/youtubei#47

**Comment by SuspiciousLookingOwl** [comment]
@Hazmi35 upgrade `youtubei` to `0.0.1-rc.35` 😅
