### ISSUE TITLE
Music will not play (Heroku as hosting)

### ISSUE THREAD

**Issue by Jayparm** [Hazmi35/jukebox#1070]
When trying to play any song, it gives an error saying "Could not resolve the track resource" and on the heroku logs:
https://cdn.discordapp.com/attachments/947957509136711754/961952490868322304/unknown.png 

I believe this is an issue with the package youtubei, and a few other people were reporting about they having the same problem, and they found that you needed to update youtubei. On heroku, it's more hard, so maybe you want to do something about that.

Thanks for reading, enjoy your day

**Comment by KTSnowy** [comment]
I'm getting a new error today, even after updating youtubei.

```Error while processing track resource
Reason: Cannot read properties of undefined (reading 'contents')
