### ISSUE TITLE
[Feature Request] Use discord-player

### ISSUE THREAD

**Issue by mozartrafi** [Hazmi35/jukebox#223]
Hi there, I got many recommendations from my users about this.

So, I recommend you too to use this package as well, it's pretty powerful than before, because its no longer need API key and supports Spotify!

[discord-player](https://www.npmjs.com/package/discord-player)

Thanks❤️

**Comment by Hazmi35** [comment]
Spotify and SoundCloud support could be added without rewriting code to use discord-player, and for the API key, I'll maybe give users control if they want to use API or scrape HTML Data directly

**Comment by Hazmi35** [comment]
Hi, @mozartrafi #224 ETA is probably tomorrow, but I'm not sure about #225.

**Comment by mozartrafi** [comment]
Thanks, it waa a good news for me

**Comment by Hazmi35** [comment]
Well turns out that I can't finish this by today, there are too many things that I need to change, and I need to finish https://github.com/Hazmi35/youtube-api, sorry for that. but PRs are always welcomed.
