### ISSUE TITLE
Spotify and SoundCloud support?

### ISSUE THREAD

**Issue by Hazmi35** [Hazmi35/jukebox#225]
Original Issue: #223

**Comment by Hazmi35** [comment]
This maybe will affect the queue system because it needs a remake. creating discord-player equivalent or lavalink equivalent written in nodejs is probably a good idea?

**Comment by itzpauliej** [comment]
did this ever get resolved ? i am also looking for Spotify and soundclound to be added but im not good with coding

**Comment by Hazmi35** [comment]
> did this ever get resolved ? i am also looking for Spotify and soundclound to be added but im not good with coding

This could be resolved after #633, code is already here, I have not pushed it nor tested it, been busy with school this week, sorry. Exam's near

**Comment by Hazmi35** [comment]
This would be continued on #739 and #748
