### ISSUE TITLE
[BUG] Player still looping after the queue deleted (Queue Timeout).

### ISSUE THREAD

**Issue by ItzMeDwii** [Hazmi35/jukebox#272]
Bot still looping queue (Repeat mode: ALL) & play the song(s) after queue deleted because there's no anyone in the voice channel.

NodeJS version: 14.15.1 LTS
Bot version: 4.22.0 (Latest)

How to reproduce:
1. Join a voice channel.
2. Play a song.
3. Run Repeat All command.
4. Leave the channel.
5. Wait until the queue got deleted and see the song still playing.

12:30 UTC+7 - 09/12/2020

**Comment by Hazmi35** [comment]
Could you please try to reproduce the problem with #273?

**Comment by ItzMeDwii** [comment]
> Could you please try to reproduce the problem with #273?

I have reproduce the problem, there's no problem & the queue timeout do the job well.

**Comment by Hazmi35** [comment]
Okay thanks, I'll merge #273 and then release it as 4.22.1

**Comment by Hazmi35** [comment]
[4.22.1](https://github.com/Hazmi35/jukebox/releases/tag/4.22.1) is now available, Docker images are still being built
