### ISSUE TITLE
[Bug Report] Cooldown is not working, maybe?

### ISSUE THREAD

**Issue by mzrtamp** [Hazmi35/jukebox#355]
:wave: Hi there, I came from [my project](https://github.com/zhycorp/disc-11) and just found this issue

> ![image](https://user-images.githubusercontent.com/40928387/107107746-adb15e00-6865-11eb-9165-ea470b6690f5.png)

This happens to every command not just [play](https://github.com/Hazmi35/jukebox/blob/main/src/commands/PlayCommand.ts), and of course including the [skip](https://github.com/Hazmi35/jukebox/blob/main/src/commands/SkipCommand.ts) command too
Hopefully, this can notify you about this problem.

**Comment by Hazmi35** [comment]
No, this is working as intended, bot owners can bypass message cooldowns
