### ISSUE TITLE
[Changes Request] Reduce impressions of spam

### ISSUE THREAD

**Issue by mzrtamp** [Hazmi35/jukebox#356]
Hello, I have a request or maybe just a suggestion about [Jukebox](https://github.com/Hazmi35/jukebox)'s messaging

In the first section, I will discuss the [play](https://github.com/Hazmi35/jukebox/blob/main/src/commands/PlayCommand.ts) command

> ![image](https://user-images.githubusercontent.com/40928387/107107897-a76fb180-6866-11eb-902e-0ce7d304ef37.png)

- Isn't the message "added to the queue" better if it isn't displayed if the user only plays 1 music?

Let's move to the second thing, it's similar to the first one, [skip](https://github.com/Hazmi35/jukebox/blob/main/src/commands/SkipCommand.ts) command

> ![image](https://user-images.githubusercontent.com/40928387/107107979-367cc980-6867-11eb-954d-5812cd3a5206.png)

- In my opinion, it is better if the user executes this command and the bot does not display the "Skipped" message if after the queue there are still other songs. Maybe you can delete it and make a new statement? or just changing the promises to add reactions like [Groovy](https://groovy.bot/)'s skip command?

> ![image](https://user-images.githubusercontent.com/40928387/107108073-fcf88e00-6867-11eb-93c9-bfd5e2117053.png)

This is useful so that it is more precise with your goal on yesterday's [commit](https://github.com/Hazmi35/jukebox/commit/aa9f4bb62af8ff314bbc4b5484a8853f7ebfa01c), which is to reduce messages that seem spammy (#354)

That's all, nothing I can do 😕

**Comment by Hazmi35** [comment]
Yesterday's commit goal is to reduce spammy messages triggered internally, not by the user, it is probably nice to delete the skip message after x seconds, but I'll leave it like this for now.
