### ISSUE TITLE
[error]: TypeError: this.client.config.owners.includes is not a function

### ISSUE THREAD

**Issue by SploeCyber** [Hazmi35/jukebox#38]
![Screenshot_2563_0507_194700](https://user-images.githubusercontent.com/37950018/81296208-c1901f80-909b-11ea-977d-23e1ca6e71a8.png)

**Comment by Hazmi35** [comment]
How do you set CONFIG_OWNERS environment variables?

**Comment by SploeCyber** [comment]
Done, I already set everything

**Comment by Hazmi35** [comment]
Did you used deploy to heroku button?

**Comment by SploeCyber** [comment]
I've fixed it. I've changed the branch to master. It works.

**Comment by Hazmi35** [comment]
Hi, It's great to see it's working now, but I don't recommend sticking on master branch, I'll also will release version v2.4.1 which fix this issue, I'll inform you again when it's done

**Comment by Hazmi35** [comment]
v2.4.2 is up!
