### ISSUE TITLE
Stage Channel Support

### ISSUE THREAD

**Issue by KurokuTetsuya** [Hazmi35/jukebox#414]
Discord just released *Stage channels*, a new type of channel that allow you to share a focused conversation with select speakers to an audience of listeners. Currently music bot doesn't support to join this channel. So, I open this issue for that. Since discord.js still doesn't support new API, you can see this PR for reference https://github.com/discord/discord-api-docs/pull/2751
The idea is extending discord.js structures for temporary until discord.js fully supported stage channels.

**Comment by KurokuTetsuya** [comment]
or this pr https://github.com/discordjs/discord.js/pull/5456

**Comment by mzrtamp** [comment]
+1

**Comment by 21Z** [comment]
the pr is merged into master version.

**Comment by Hazmi35** [comment]
Should be fixed if v5 is released #293
