### ISSUE TITLE
YouTube Music Support

### ISSUE THREAD

**Issue by KurokuTetsuya** [Hazmi35/jukebox#451]
https://music.youtube.com based on https://youtube.com. So, adding replacing URL support for YouTube music should be a good idea

**Comment by Hazmi35** [comment]
The /watch endpoint on YouTube music is already supported? can you elaborate?

**Comment by KurokuTetsuya** [comment]
![image](https://user-images.githubusercontent.com/45705890/116833098-8c9ca700-abe1-11eb-9608-95d8ff8eb8b1.png)
Playlist load seems doesn't work. I'm using scrape anyway
