### ISSUE TITLE
[Feature Request] Auto-select the only search result

### ISSUE THREAD

**Issue by mzrtamp** [Hazmi35/jukebox#474]
Meresahkan

![image](https://user-images.githubusercontent.com/40928387/118344021-4f77d380-b556-11eb-9cf8-880ee222e34b.png)

Or, is this a feature request?

> Immediately allow selecting the existing results if it only has 1 because this is from a video link

**Comment by Hazmi35** [comment]
This happens because the URL is "youtu.be" and not "youtube.com" and has no "?v=" parameters, but Immediately selecting the only search result is a good feature idea

**Comment by Hazmi35** [comment]
Fixed in #480
