### ISSUE TITLE
[YTDLError: aborted] Facing this in Heroku.

### ISSUE THREAD

**Issue by FireUpdate** [Hazmi35/jukebox#547]
Haven't changed anything, Just deployed the app through the "Deploy to Heroku" button, and it keeps telling me Error while playing music Reason: YTDLError: aborted. - How do I fix this?

**Comment by Hazmi35** [comment]
Does this happen at the start of the music?

**Comment by FireUpdate** [comment]
@Hazmi35 In middle of a track. (Never happend to me in the starting of any tracks.) The error pops in and the bot leaves the voice channel.

**Comment by Hazmi35** [comment]
Is it just specific to one tracks? can't reproduce

**Comment by FireUpdate** [comment]
Nope, I tried with some songs it happens. Is there any extra builbacks or something we need to add?

**Comment by Hazmi35** [comment]
> Nope, I tried with some songs it happens. Is there any extra builpacks or something we need to add?

No, heroku/nodejs is the only thing you need, because ffmpeg is already installed in node_modules by ffmpeg-static, what's your Heroku stack? trying to reproduce again
