### ISSUE TITLE
Discord.js v13 Migration

### ISSUE THREAD

**Issue by mzrtamp** [Hazmi35/jukebox#588]
[discord.js](https://github.com/discordjs/discord.js) Finally releases its new [stable (branch) version](https://github.com/discordjs/discord.js/releases/tag/13.0.0) but requires Node [`16.6`](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.6.1) or higher to use. This version comes with [Slash commands](https://discordjs.guide/additional-info/changes-in-v13.html#slash-commands), [StageChannel](https://discordjs.guide/additional-info/changes-in-v13.html#stagechannel), [Sticker](https://discordjs.guide/additional-info/changes-in-v13.html#sticker), [Threads](https://discordjs.guide/additional-info/changes-in-v13.html#threads) support, [Message components](https://discordjs.guide/additional-info/changes-in-v13.html#message-components) update, new different typings, and some breaking changes that will be referenced to this [HTML page](https://discordjs.guide/additional-info/changes-in-v13.html). I hope you can maintain this major (maybe) changes ASAP, thanks for your appreciation!

**Comment by Hazmi35** [comment]
Please see #293
