### ISSUE TITLE
YTDLError: aborted issues on Jukebox v5

### ISSUE THREAD

**Issue by KTSnowy** [Hazmi35/jukebox#653]
"Error while playing music
Reason: YTDLError: aborted"

It happens around the middle/end of every song I tried.

**Comment by Hazmi35** [comment]
Are you using v5? currently, v5 is not stable, and this is a known issue, please use v4 for now from the releases section

Related: https://github.com/Hazmi35/jukebox/issues/633#issuecomment-901212621
