### ISSUE TITLE
STATUS_TYPE environment variable issue

### ISSUE THREAD

**Issue by KTSnowy** [Hazmi35/jukebox#657]
The config.ts file checks for a STATUS_TYPE environment variable while the app.json asks for a CONFIG_STATUS_TYPE variable, causing the bot to not change it's status type when changing CONFIG_STATUS_TYPE on Heroku.

**Comment by Hazmi35** [comment]
Fixed in #658, also backported to v4 in dc15ba3c5665dafc53baeb08f80e393776d1ed21, released as [Version 4.42.3](https://github.com/Hazmi35/jukebox/releases/tag/4.42.3)
