### ISSUE TITLE
Error during heroku build

### ISSUE THREAD

**Issue by Salvi0** [Hazmi35/jukebox#700]
The bot fail to build to heroku when the deploy button on the repo is pressed and all the values are filled.
[proof](https://ezic.report.sys.salvi0.xyz/media/msedge_ALCYKIoZSK.png).
I think this might be a problem with the last update.

**Comment by Hazmi35** [comment]
Hmm seems like Heroku still uses the old Docker build system (not BuildKit). 
Hang on, I'm trying to reproduce this on my Docker

**Comment by Hazmi35** [comment]
Yeah, could reproduce
