### ISSUE TITLE
Add Spotify source support

### ISSUE THREAD

**Issue by apoorvcodes** [Hazmi35/jukebox#739]
Feat[request] : add spotify api to fetch user profile and playlists and artist

**Comment by apoorvcodes** [comment]
If you approve working on this kindly assign me

**Comment by Hazmi35** [comment]
This is probably related to #225, I'm not sure what you mean by profile tough

**Comment by apoorvcodes** [comment]
refrence: https://developer.spotify.com/documentation/web-api/

**Comment by apoorvcodes** [comment]
its not about the player its about getting info about playlists and users from spotify as bot is based on music this would be a great addition

**Comment by Hazmi35** [comment]
Ah I see, PR are always welcome

**Comment by apoorvcodes** [comment]
sure ill start working then
kindly assign me this ?

**Comment by Hazmi35** [comment]
Why was this closed?
