### ISSUE TITLE
I can't play YouTube music using the URL.

### ISSUE THREAD

**Issue by AI-Avalon** [Hazmi35/jukebox#750]
I'm using version 5.0.1, but if you copy it from YouTube sharing and specify it at the time of playback, it will be an Invalid YouTube URL and you can't play the song with the URL. Is there a solution?

**Comment by Hazmi35** [comment]
Ah do you mean youtu.be URLs? I completely forgot about that 😅, currently seeking is not a possible feature, but that is actually planned

**Comment by Hazmi35** [comment]
Should be fixed with the latest release
