### ISSUE TITLE
Raspberry Pi 3B - corrupted double-linked list

### ISSUE THREAD

**Issue by XaaRii** [Hazmi35/jukebox#900]
I'm having problems with running this on raspberry pi - Raspbian Buster.
I'm not using docker, since it screwed up my raspberry and i had to reinstall it few days ago.

When i install with optional dependencies, everything looks alright but when i start it, everything loads and then it instantly crashes on:
`corrupted double-linked list`
`Aborted`

When i install without optional dependencies, it works fine until i want to play a music, when it finds the video, probably downloads it as well but when it wants to start playing, bot crashes/restarts with a message that i'm missing _a valid encryption package, such as sodium, libsodium-wrappers or tweetnacl_
Separately tried to install each one of them, but when these packages are installed, it goes back to `corrupted double-linked list` problem.

Any help or suggestions would be greatly appreciated, as i have genuinely no clue what to do to fix it.

**Comment by Hazmi35** [comment]
tweetnacl is installed by default if you don't install the optional dependencies, sodium is kinda outdated, I recommend you using libsodium-wrappers, can you send here the full error?

**Comment by XaaRii** [comment]
where can i find full error log? or do you want only what shows in the console?
if that's so, then here you have installation with optional dependencies: https://pastebin.com/g9v6Hgny
and here installation without: https://pastebin.com/hGMcsFSm

**Comment by Hazmi35** [comment]
Wait, `tweetnacl` should be installed by default, you sure you're installing it with `npm install --no-optional` ? try deleting node_modules and reinstalling it without no optional dependencies.

Also what do you install on the one with optional dependencies? Jukebox uses `libsodium-wrappers` in the package.json as a optionalDependencies (so `npm install` should installs it), `sodium` is rather outdated and I expect them not working with latest Node.js

**Comment by Hazmi35** [comment]
> Wait, `tweetnacl` should be installed by default, you sure you're installing it with `npm install --no-optional` ? try deleting node_modules and reinstalling it without no optional dependencies.
> 
> Also what do you install on the one with optional dependencies? Jukebox uses `libsodium-wrappers` in the package.json as a optionalDependencies (so `npm install` should installs it), `sodium` is rather outdated and I expect them not working with latest Node.js

If somehow tweetnacl is not installed, then try installing it manually

**Comment by XaaRii** [comment]
seems like tweetnacl isn't here/isn't recognized.    https://pastebin.com/8Ar1fUVP

on the one with optional dependencies, i just do normal npm install, and there were no errors, so i guess it uses `libsodium-wrappers `from the package.json

also i should probably note that i'm trying to use clone of this repository made few hours ago.

**Comment by XaaRii** [comment]
gotta go, i should be back in 1-2 hours

**Comment by XaaRii** [comment]
Linux rp3pawele 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux

**Comment by XaaRii** [comment]
> > Wait, `tweetnacl` should be installed by default, you sure you're installing it with `npm install --no-optional` ? try deleting node_modules and reinstalling it without no optional dependencies.
> > Also what do you install on the one with optional dependencies? Jukebox uses `libsodium-wrappers` in the package.json as a optionalDependencies (so `npm install` should installs it), `sodium` is rather outdated and I expect them not working with latest Node.js
> 
> If somehow tweetnacl is not installed, then try installing it manually

I somehow missed this message. Yeah i tried installing `tweetnacl` into clean installation with `--no-optional`, but then it crashed on the beginning with the `corrupted double-linked list` error.
also i completely forgot about the debug info switch in .env, so i switched it on as it may say something useful (hopefully).
log from the installation, if you're interested: https://pastebin.com/LtY3ZNet

I noticed the Session Limit Information with total and remaining values, and i wonder:
- why is it not regenerating from yesterday (i think i did indeed execute `npm start` ~23 times so far)
- what will happen when it reaches zero.

**Comment by Hazmi35** [comment]
Hello, I've found what is causing this issue.

Actually, I want to say that I'm missreads the issue, I thought the `corrupted double-linked list` is occuring when the bot tries to play a music, but it's actually when the bot client is ready.

And this issue actually has 2 issues, one is #901 and the other one is this `corrupted double-linked list` issue, the libsodium libraries and tweetnacl has nothing to do with the second issue.

The second issue was, erlpack was not functioning properly on Raspberry PI with ARMv7 architecture. It will throw `corrupted double-linked list` and sometimes segfault. So with that, all the optional dependencies is actually working properly except erlpack.

The current workaround is: Uninstall erlpack using `$ npm remove erlpack` and you're good to go

I'll close this issue and forward this to a new issue.
